import Head from "next/head";
import Section from "../components/Section";
import SideBar from "../components/SideBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <div className="grid grid-cols-9 gap-3">
      <SideBar />
      <Section />
    </div>
    </div>
  );
}
